# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(max_length=1024),
        ),
    ]
