# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171104_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='score',
        ),
    ]
