# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='raters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
