# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171103_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.PositiveIntegerField(default=1146591361),
        ),
    ]
