# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171104_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rating',
            new_name='rep',
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.PositiveIntegerField(default=1916071621),
        ),
    ]
